const ActionTypes = /* ::Object.freeze( */ {
  FETCH_START: 'FETCH_START',
  FETCH_END: 'FETCH_END',
  FETCH_INVENTORY_DETAILS: 'FETCH_INVENTORY_DETAILS',
  FETCH_INVENTORY_DETAILS_SUCCEEDED: 'FETCH_INVENTORY_DETAILS_SUCCEEDED'
}

export default ActionTypes;